# Generated by Django 5.2.12 on 2026-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_medicine_description_medicine_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='Medicine', max_length=50),
        ),
    ]
