# Generated by Django 5.2.12 on 2026-03-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdrItrm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.ImageField(upload_to='')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.order')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine')),
            ],
        ),
    ]
