# Generated by Django 5.2.12 on 2026-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_order_status_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
